# Create dependabot.yml file for dependabot to create pull requests

name: Dependabot pull requests

version: 2

updates:
  - package-ecosystem: "npm"
    # Files stored in root directory
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    # Files stored in frontend directory
    # Note: Might want to exclude create react app since it gets some weird "vulnerabilities"
    directory: "/frontend"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
  # Files stored in backend directory
    directory: "/backend"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    # Workflow files stored in the
    # default location of `.github/workflows`
    directory: "/"
    schedule:
      interval: "weekly"
